# Generated by Django 4.0.4 on 2022-05-13 12:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_alter_post_bookmarked_user_alter_post_liked_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bookmarked_user',
            field=models.ManyToManyField(blank=True, default=None, related_name='bookmarked_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='liked_user',
            field=models.ManyToManyField(blank=True, default=None, related_name='post_liked_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
