# Generated by Django 4.0.4 on 2022-05-13 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_bookmarked_user_alter_post_liked_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='created_by',
        ),
    ]
