# Generated by Django 4.0.4 on 2022-05-13 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_rename_creator_group_created_by'),
        ('posts', '0007_alter_post_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_group', to='groups.group'),
        ),
    ]
