# Generated by Django 4.0.4 on 2022-05-14 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0009_alter_post_bookmarked_user_alter_post_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_by_username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
