# Generated by Django 4.0.4 on 2022-05-14 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_created_by_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_by_username',
        ),
    ]
