# Generated by Django 4.0.4 on 2022-05-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_extendeduser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='is_artist',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
