# Generated by Django 4.0.4 on 2022-05-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_extendeduser_is_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='is_artist',
            field=models.BooleanField(default=False),
        ),
    ]
