# Generated by Django 4.0.4 on 2022-05-14 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='liked_user',
        ),
    ]
