# Generated by Django 4.0.4 on 2022-05-14 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_comment_bookmarked_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='bookmarked_user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='group',
        ),
    ]
