# Generated by Django 4.0.4 on 2022-05-09 21:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('profile_picture', models.URLField()),
                ('users', models.ManyToManyField(blank=True, related_name='users_following_group', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
