# Generated by Django 4.0.4 on 2022-05-13 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_group_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='creator',
            new_name='created_by',
        ),
    ]
